In [1]:
import numpy as np
import h5py

In [3]:
#Creating 2 dataset
mat1 = np.random.random(size = (100, 100))
mat2 = np.random.random(size = (1000, 10))

In [5]:
with h5py.File("C:\\Users\Admin\\Desktop\\hdf5_data.h5", "w") as hdf:# In this command we are providing the location and HDF5 file name(hdf5_data.h5)
    #the below 2 command we are putting 2 dataset under HDF5 file(hdf5_data.h5)with name(key)data1 and data2 and Mat1 & Mat 2 is value.
    hdf.create_dataset("data1", data=mat1) 
    hdf.create_dataset("data2", data=mat2)

In [12]:
# To read the above hdf5 file(hdf5_data.h5)
with h5py.File("C:\\Users\Admin\\Desktop\\hdf5_data.h5", "r") as hdf:
    ls = list(hdf.keys())
    print("List of datasetin this file: \n", ls)
    data = hdf.get("data1")
    data1 = np.array(data)
    print("shape of data1: \n", data1.shape)
    

List of datasetin this file: 
 ['data1', 'data2']
shape of data1: 
 (100, 100)


In [13]:
f= h5py.File("C:\\Users\Admin\\Desktop\\hdf5_data.h5", "r")
ls = list(f.keys())
f.close()


In [14]:
ls

['data1', 'data2']

In [30]:
m1 = np.random.random(size = (100,100))
m2 = np.random.random(size = (100,100))
m3 = np.random.random(size = (100,100))
m4 = np.random.random(size = (100,100))
with h5py.File("C:\\Users\Admin\\Desktop\\hdf5_Group.h5", "w") as hdf:
    g1 = hdf.create_group("Group1")
    g1.create_dataset("Tata1", data = m1)
    g1.create_dataset("Tata4", data = m4)
    
    g2 = hdf.create_group("Group2/SubGroup1")
    g2.create_dataset("Tata3", data = m3)
    
    g3 = hdf.create_group("Group2/SubGroup2")
    g3.create_dataset("Tata2", data = m2)
    


In [28]:
with h5py.File("C:\\Users\Admin\\Desktop\\hdf5_Group.h5", "r") as hdf:
    data_items = list(hdf.items())
    print(data_items)
    g1 = hdf.get("Group1")
    g1_items = list(g1.items())
    print(g1_items)
    Tata = np.array(g1.get("Tata4"))
    print(Tata)
    Tata = np.array(g1.get("Tata4"))
    print(Tata)
    

[('Group1', <HDF5 group "/Group1" (2 members)>), ('Group2', <HDF5 group "/Group2" (2 members)>)]
[('Tata1', <HDF5 dataset "Tata1": shape (100, 100), type "<f8">), ('Tata4', <HDF5 dataset "Tata4": shape (100, 100), type "<f8">)]
[[0.4101778  0.46676438 0.0256162  ... 0.66070181 0.97687337 0.01599965]
 [0.25762605 0.14051285 0.0105722  ... 0.23348888 0.11108288 0.40742795]
 [0.23896032 0.88533236 0.96770699 ... 0.12702797 0.11965712 0.4895208 ]
 ...
 [0.72242456 0.95066412 0.56700204 ... 0.80234715 0.59880566 0.29366459]
 [0.62472903 0.33410964 0.10598298 ... 0.3326326  0.84257759 0.88123917]
 [0.30206672 0.54550218 0.92477186 ... 0.10730137 0.92667563 0.33685546]]


In [39]:
with h5py.File("C:\\Users\Admin\\Desktop\\hdf5_Group.h5", "r") as hdf:
    data_items = list(hdf.items()) 
    g2 = hdf.get("Group2")
    g2_items = list(g2.items())
    print(g2_items)
    g2 = hdf.get("Group2")
    g2_items = list(g2.items())
    g21_items = g21.keys()
    g21 = g2.get("SubGroup1")
    tata3 = np.array(g21.get("Tata3"))
    print(tata3)
import pandas as pd
df = pd.DataFrame(tata3)
print(df)
DF_to_CSV = df.to_csv(C:\Users\Admin\Desktop\df.csv, sep='\t')

[('SubGroup1', <HDF5 group "/Group2/SubGroup1" (1 members)>), ('SubGroup2', <HDF5 group "/Group2/SubGroup2" (1 members)>)]
[[0.44595472 0.38995794 0.82576099 ... 0.11621285 0.81057655 0.45636813]
 [0.9896426  0.77828478 0.92067481 ... 0.32102154 0.72247373 0.41605893]
 [0.85534343 0.24979548 0.30736081 ... 0.39513793 0.70848562 0.56331537]
 ...
 [0.07196739 0.65413179 0.44702466 ... 0.10920691 0.11161692 0.50680538]
 [0.83350928 0.34215852 0.15113053 ... 0.96796455 0.32448973 0.33627883]
 [0.56125044 0.77782583 0.53331132 ... 0.85216551 0.50144198 0.39034979]]
          0         1         2         3         4         5         6   \
0   0.445955  0.389958  0.825761  0.882274  0.952886  0.377990  0.600125   
1   0.989643  0.778285  0.920675  0.719780  0.377362  0.836333  0.699125   
2   0.855343  0.249795  0.307361  0.218156  0.831821  0.706564  0.492136   
3   0.096197  0.142981  0.079545  0.552967  0.866360  0.591361  0.762634   
4   0.189933  0.951519  0.328507  0.545792  0.384068 

In [45]:
DF_to_CSV = df.to_csv("C:\\Users\\Admin\Desktop\\df.csv", sep='\t', index = False, header = False)